name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # 24時間に一回実行されます
    - cron: "0 0 * * *" # 毎日午前0時に実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: kenya6565